---
# node1 node variables
# combined with contents of original file node-hp-2.yml
############################
# x86 variables - originally from node-hp-1.yml
############################

autoinstall:
  network:
    version: 2
    ethernets:
      enp0s3:
        dhcp4: false
        dhcp6: false
        addresses:
          - "{{ ip }}/24"
        routes:
          - to: default
            via: "{{ default_gateway }}"
        nameservers:
          addresses:
            - "{{ dns_server }}"
          search:
            - "{{ dns_domain }}"
  storage:
    grub:
      reorder_uefi: false
    config:
      - ptable: gpt
        path: /dev/sda
        wipe: superblock-recursive
        preserve: false
        name: ''
        grub_device: false
        type: disk
        id: disk-sda
      - device: disk-sda
        size: 1075M
        wipe: superblock
        flag: boot
        number: 1
        preserve: false
        grub_device: true
        path: /dev/sda1
        type: partition
        id: partition-0
      - fstype: fat32
        volume: partition-0
        preserve: false
        type: format
        id: format-0
      - device: disk-sda
        size: 2G
        wipe: superblock
        number: 2
        preserve: false
        grub_device: false
        path: /dev/sda2
        type: partition
        id: partition-1
      - fstype: ext4
        volume: partition-1
        preserve: false
        type: format
        id: format-1
      - device: disk-sda
        size: -1
        wipe: superblock
        number: 3
        preserve: false
        grub_device: false
        path: /dev/sda3
        type: partition
        id: partition-2
      - name: ubuntu-vg
        devices:
          - partition-2
        preserve: false
        type: lvm_volgroup
        id: lvm_volgroup-0
      - name: ubuntu-lv
        volgroup: lvm_volgroup-0
        size: 30G
        wipe: superblock
        preserve: false
        path: /dev/ubuntu-vg/ubuntu-lv
        type: lvm_partition
        id: lvm_partition-0
      - fstype: ext4
        volume: lvm_partition-0
        preserve: false
        type: format
        id: format-3
      - path: /
        device: format-3
        type: mount
        id: mount-3
      - name: lv-data
        volgroup: lvm_volgroup-0
        size: -1
        wipe: superblock
        preserve: false
        path: /dev/ubuntu-vg/lv-data
        type: lvm_partition
        id: lvm_partition-1
      - fstype: ext4
        volume: lvm_partition-1
        preserve: false
        type: format
        id: format-4
      - path: /storage
        device: format-4
        type: mount
        id: mount-4
      - path: /boot
        device: format-1
        type: mount
        id: mount-1
      - path: /boot/efi
        device: format-0
        type: mount
        id: mount-0

########################
# Bind9 role variables
########################

bind9_authoritative: true
bind9_forward: false
bind9_recursor: false
bind9_forward_servers: []
bind9_generate_ddns_key: true
bind9_zones:
  - name: "{{ dns_domain }}"
    type: primary
    ddns_update_key: ddnskey
    ddns_update_policy_grant: "zonesub any"
    secondary_servers:
      - 'key "ddnskey"'
    default_ttl: 600
    serial: 2024102002
    refresh: 1D
    retry: 2H
    expire: 1000H
    primary: "ns.{{ dns_domain }}"
    admin: "admin.{{ dns_domain }}"
    ns_records:
      - "ns.{{ dns_domain }}"
    # RR values are either relative to the zone, either with a final dot when outside.
    rrs:
      - label: gateway
        type: A
        rdata: 10.0.0.1
      - label: ns
        type: A
        rdata: 10.0.0.11
      - label: node1
        type: A
        rdata: 10.0.0.11
      - label: node2
        type: A
        rdata: 10.0.0.12
      - label: node3
        type: A
        rdata: 10.0.0.13
      - label: node4
        type: A
        rdata: 10.0.0.14
      - label: node5
        type: A
        rdata: 10.0.0.15
      - label: node6
        type: A
        rdata: 10.0.0.16
      - label: node7
        type: A
        rdata: 10.0.0.17
      - label: node8
        type: A
        rdata: 10.0.0.18
      - label: node9
        type: A
        rdata: 10.0.0.19
      - label: vault
        type: A
        rdata: 10.0.0.11
  - name: 0.10.in-addr.arpa
    type: primary
    default_ttl: 600
    serial: 2024102001
    refresh: 1D
    retry: 2H
    expire: 1000H
    primary: "ns.{{ dns_domain }}"
    admin: "admin.{{ dns_domain }}"
    ns_records:
      - "ns.{{ dns_domain }}."
    rrs:
      - label: 1.0
        type: PTR
        rdata: "gateway.{{ dns_domain }}."
      - label: 11.0
        type: PTR
        rdata: "node1.{{ dns_domain }}."
      - label: 12.0
        type: PTR
        rdata: "node2.{{ dns_domain }}."
      - label: 13.0
        type: PTR
        rdata: "node3.{{ dns_domain }}."
      - label: 14.0
        type: PTR
        rdata: "node4.{{ dns_domain }}."
      - label: 15.0
        type: PTR
        rdata: "node5.{{ dns_domain }}."
      - label: 16.0
        type: PTR
        rdata: "node6.{{ dns_domain }}."
      - label: 17.0
        type: PTR
        rdata: "node7.{{ dns_domain }}."
      - label: 18.0
        type: PTR
        rdata: "node8.{{ dns_domain }}."
      - label: 19.0
        type: PTR
        rdata: "node9.{{ dns_domain }}."

############################
# restic backup role variables
############################
restic_clean_service: true
