---
all:
  children:
    control:
      hosts:
        pimaster:
          hostname: pimaster
          ansible_host: localhost
          ansible_connection: local
    external:
      hosts:
        s3:
          hostname: s3
          ansible_host: s3.ricsanfre.com
    picluster:
      hosts:
        node1:  # AMD Ryzen 3 Pro, 256GB M.2, 480GB SATA SSD, 1 x 8GB SODIMM
          hostname: node1
          ansible_host: 10.0.0.11
          ip: 10.0.0.11
          mac: b0:5c:da:38:18:13
        node2:  # AMD Ryzen 3 Pro, 256GB M.2, 500GB SATA HDD, 1 x 8GB SODIMM
          hostname: node2
          ansible_host: 10.0.0.12
          ip: 10.0.0.12
          mac: b0:5c:da:39:46:22
        node3:  # AMD Ryzen 3 Pro, 256GB M.2, 500GB SATA HDD, 1 x 8GB SODIMM
          hostname: node3
          ansible_host: 10.0.0.13
          ip: 10.0.0.13
          mac: b0:5c:da:38:12:61
        node4:  # AMD Ryzen 5 Pro, 256GB M.2, 500GB SATA HDD, 1 x 16GB SODIMM
          hostname: node4
          ansible_host: 10.0.0.14
          ip: 10.0.0.14
          mac: b0:0c:d1:53:97:ce
        node5:  # AMD Ryzen 5 Pro, 256GB M.2, 500GB SATA HDD, 1 x 16GB SODIMM
          hostname: node5
          ansible_host: 10.0.0.15
          ip: 10.0.0.15
          mac: b0:0c:d1:53:8d:f3
        node6:  # AMD Ryzen 5 Pro, 256GB M.2, 500GB SATA HDD, 2 x 8GB SODIMM
          hostname: node6
          ansible_host: 10.0.0.16
          ip: 10.0.0.16
          mac: 80:e8:2c:20:58:0c
        node-hp-7:  # AMD Ryzen 5 Pro, 256GB M.2, 500GB SATA HDD, 2 x 8GB SODIMM
          hostname: node7
          ansible_host: 10.0.0.17
          ip: 10.0.0.17
          mac: 7c:57:58:0e:48:56
        #node8:
        #  hostname: node8
        #  ansible_host: 10.0.0.18
        #  ip: 10.0.0.18
        #  mac: d8:3a:dd:0d:be:c8
        #node9:
        #  hostname: node9
        #  ansible_host: 10.0.0.19
        #  ip: 10.0.0.19
        #  mac: d8:3a:dd:0d:be:c8
    #raspberrypi:
    #  hosts:
    #    node[1:6]:
    x86:
      hosts:
        node[1:7]:
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            node[1:3]:
        k3s_worker:
          hosts:
            node[4:7]:
    dns:
      hosts:
        node1:
    pxe:
      hosts:
        node1:
    vault:
      hosts:
        node1:
    haproxy:
      hosts:
        node1:
    san:
      hosts:
        node1:
